const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
function setup(){const storage=new Map();const context={Date,Math,JSON,Object,Set,Event:class{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{dispatchEvent(){}}};vm.createContext(context);for(const file of ['config.js','data.js','model.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist',file),'utf8'),context);return context.window.ConnextModel;}
test('seed stories produce the intended explainable priority queue',()=>{const m=setup(),d=m.get();assert.equal(d.students.length,10);assert.equal(d.departments.length,12);const q=d.students.map(s=>({id:s.id,...m.flags(s,d)})).sort((a,b)=>b.score-a.score);assert.equal(q[0].id,'aanya');assert.equal(q.find(s=>s.id==='aanya').flags.length,3);assert.equal(q.find(s=>s.id==='ishita').flags[0].type,'multi');assert.equal(q.filter(s=>s.flags.length).length,7);for(const s of q)for(const f of s.flags)assert.ok(f.reason.length>15);assert.equal(q.find(s=>s.id==='simran').score,0);});
test('permission projection removes private counselling and hides grievance',()=>{const m=setup();for(const role of ['coordinator','fees','hostel','academics','placement','student']){const text=JSON.stringify(m.get(role));assert.ok(!text.includes('Reports low mood'));assert.ok(!text.includes('Confidential grievance support'));}assert.ok(JSON.stringify(m.get('counsellor')).includes('Reports low mood'));assert.ok(JSON.stringify(m.get('grievance')).includes('Confidential grievance support'));assert.equal(m.permission({sensitivity:'restricted',restrictedTo:['counsellor']},'fees'),'redacted');assert.equal(m.permission({sensitivity:'restricted',restrictedTo:['grievance'],hideExistence:true},'coordinator'),'hidden');});
test('hold and accepted handoff clear the corresponding flags and append events',()=>{const m=setup();let d=m.get(),n=d.events.length;m.mutate('hold',{studentId:'aanya'},'fees');d=m.get();assert.equal(d.students.find(s=>s.id==='aanya').hold,true);assert.ok(!m.flags(d.students[0],d).flags.some(f=>f.type==='reminder'));m.mutate('accept',{id:'HO-101'},'counsellor');d=m.get();assert.ok(!m.flags(d.students[0],d).flags.some(f=>f.type==='referral'));assert.ok(d.events.length>=n+2);assert.equal(d.handoffs[0].status,'Accepted');});
test('unauthorised edits are rejected by the model',()=>{const m=setup();assert.throws(()=>m.mutate('accept',{id:'HO-101'},'fees'));assert.throws(()=>m.mutate('status',{id:m.get().cases[0].id,status:'Resolved'},'fees'));assert.throws(()=>m.mutate('hold',{studentId:'aanya'},'student'));});
test('booking clears appointment wait; task completion and notes persist',()=>{const m=setup();const c=m.get().cases.find(c=>c.studentId==='riya');m.mutate('appointment',{id:c.id,date:new Date(Date.now()+86400000).toISOString()},'counsellor');m.mutate('task',{id:'t-5',done:true},'counsellor');m.mutate('note',{studentId:'riya',department:'wellbeing',text:'Private demo check-in',restricted:true},'counsellor');m.reload();const d=m.get('counsellor');assert.equal(m.flags(d.students.find(s=>s.id==='riya'),d).flags.length,0);assert.equal(d.tasks.find(t=>t.id==='t-5').done,true);assert.ok(!JSON.stringify(m.get('fees')).includes('Private demo check-in'));});
test('offline intake produces connected records and matching department tasks',()=>{const m=setup();const text='I need help with my fees, scholarship and missed classes.';const result=m.intake(text);assert.deepEqual(Array.from(result.departments),['fees','scholarships','academics']);const ids=m.mutate('intake',{...result,text,studentId:'simran'},'coordinator');const d=m.get(),cases=d.cases.filter(c=>ids.includes(c.id));assert.equal(cases.length,3);assert.equal(new Set(cases.map(c=>c.journeyId)).size,1);assert.equal(d.tasks.filter(t=>ids.includes(t.caseId)).length,3);m.reset();assert.equal(m.get().cases.length,21);assert.equal(m.get().students.find(s=>s.id==='aanya').hold,false);});
test('mixed-department intake does not disclose sensitive original text to Fees',()=>{const m=setup(),text='I have low mood and cannot pay my fees.';m.mutate('intake',{...m.intake(text),text,studentId:'aanya'},'coordinator');assert.ok(!JSON.stringify(m.get('fees')).includes(text));assert.ok(JSON.stringify(m.get('counsellor')).includes(text));});
